import React,{useState} from 'react';
import ReviewGallery from './ReviewGallery';
import {downloadListing,listingText} from './listingExport';

export default function ProductReview({draft,change,onInspect,onPhotos,onGenerate,busy,issues,onMatch,products,search,setSearch,onCompare,dirty}){
 const d=draft.data;const [exporting,setExporting]=useState(false),[notice,setNotice]=useState('');
 const field=(key,label,type='text')=><label className="cs-field" key={key}><span>{label}</span><input type={type} inputMode={type==='number'?'decimal':undefined} min={type==='number'?'0':undefined} step={type==='number'?'any':undefined} value={d[key]??''} onChange={e=>change(key,e.target.value)}/></label>;
 async function download(){setExporting(true);try{await downloadListing(d,setNotice);}catch(e){setNotice(e.message);}finally{setExporting(false);}}
 return <div className="cs-simple-review">
  <section className="cs-panel cs-export-bar"><div><h2>Product review</h2><p>Check the photos and facts. Save, export or publish.</p></div><div className="cs-row-actions"><button type="button" disabled={exporting} onClick={download}>{exporting?'Preparing…':'Download photos + details ↓'}</button><a className="cs-external-link" href="https://sellercentral.amazon.in/product-search" target="_blank" rel="noopener noreferrer">Open Seller Central ↗</a></div>{notice&&<p role="status">{notice}</p>}</section>
  <div className="cs-review-columns"><section className="cs-panel"><div className="cs-section-heading"><h2>1. Photos</h2><button type="button" onClick={onPhotos}>Replace / add</button></div><ReviewGallery key={draft.id} photos={d.photos} onInspect={onInspect}/><p className="cs-caption">Check: sharp detail · enough light · full product · clean background.</p>{Object.entries(d.photos||{}).filter(([,p])=>p.warning).map(([key,p])=><p key={key} className="cs-warning">{key}: {p.warning}</p>)}<label className="cs-check"><input type="checkbox" checked={!!d.imageQualityApproved} onChange={e=>change('imageQualityApproved',e.target.checked)}/>Photos checked</label>{d.video?.url&&<details><summary>360° video</summary><video src={d.video.url} controls playsInline preload="none" style={{width:'100%'}}/></details>}<label className="cs-check"><input type="checkbox" checked={!!d.keepExistingPhotos} onChange={e=>change('keepExistingPhotos',e.target.checked)}/>Keep existing website photos too</label></section>
  <section className="cs-panel"><h2>2. Name & description</h2>{field('name','Product name')}<div className="cs-fields">{field('category','Category')}{field('material','Material')}{field('unit','What is included?')}</div><label className="cs-field"><span>Description</span><textarea rows="5" value={d.notes||''} onChange={e=>change('notes',e.target.value)} placeholder="Describe this exact product. You can paste reviewed Amazon or Canva copy here."/></label><label className="cs-field"><span>Highlights · one per line</span><textarea rows="3" value={(d.marketing?.highlights||[]).join('\n')} onChange={e=>change('marketing',{...d.marketing,highlights:e.target.value.split('\n')})}/></label><details><summary>Writing help & Amazon reference</summary><button type="button" disabled={busy||!Object.keys(d.photos||{}).length} onClick={onGenerate}>Draft description with AI</button><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(listingText(d));setNotice('Product details copied.');}catch{setNotice('Copy unavailable. Use Download photos + details.');}}}>Copy details for Amazon AI</button><p>Review AI text before saving. ZIP includes JPG photos, originals and details; unzip before uploading.</p>{field('asin','Existing Amazon ASIN')}{field('sellerSku','Amazon seller SKU')}</details></section></div>
  <section className="cs-panel"><h2>3. Measurements</h2><div className="cs-measure-grid">{[['Product',''],['With packaging','packed_']].map(([label,prefix])=><div key={label}><h3>{label}</h3><div className="cs-fields">{[['length','Length · cm'],['width','Width · cm'],['height','Height · cm'],['weight_g','Weight · g']].map(([key,label])=>field(prefix+key,label,'number'))}</div></div>)}</div></section>
  <section className="cs-panel"><h2>4. Stock & price</h2>{(d.locations||[]).map((loc,i)=><div className="cs-fields" key={i}>{[['name','Location'],['sellable','Sellable quantity'],['damaged','Damaged quantity']].map(([key,label])=><label className="cs-field" key={key}><span>{label}</span><input type={key==='name'?'text':'number'} min="0" step="1" value={loc[key]??''} onChange={e=>change('locations',d.locations.map((x,j)=>j===i?{...x,[key]:e.target.value}:x))}/></label>)}</div>)}<div className="cs-fields">{field('cost_price','Cost ₹ · private','number')}{field('mrp','Selling price ₹','number')}</div><label className="cs-check"><input type="checkbox" checked={!!d.pricingApproved} onChange={e=>change('pricingApproved',e.target.checked)}/>Prices checked</label><label className="cs-check"><input type="checkbox" checked={!!d.allLocations} onChange={e=>change('allLocations',e.target.checked)}/>All locations counted</label><label className="cs-check"><input type="checkbox" checked={!!d.stockConfirmed} onChange={e=>change('stockConfirmed',e.target.checked)}/>Stock is with Decorbeats and ready to fulfil</label>{d.locationPhoto?.url&&<details><summary>Storage photo</summary><img className="cs-reference" src={d.locationPhoto.url} alt="Storage location"/></details>}</section>
  <section className="cs-panel"><h2>5. Website destination</h2>{draft.product_id?<><p>Updates the matched inventory product.</p><button type="button" disabled={dirty||busy} onClick={onCompare}>Compare current inventory</button></>:<><div className="cs-row-actions"><button type="button" aria-pressed={d.destination==='new'} onClick={()=>change('destination','new')}>Create new product {d.destination==='new'?'✓':''}</button><button type="button" aria-pressed={d.destination==='existing'} onClick={()=>change('destination','existing')}>Match existing product {d.destination==='existing'?'✓':''}</button></div>{d.destination==='existing'&&<><input aria-label="Find matching product" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or SKU"/><div className="cs-match-list">{products.slice(0,6).map(p=><button type="button" key={p.id} onClick={()=>onMatch(p)}><img src={p.image_url||'/assets/images/product-fallback.svg'} alt=""/><span>{p.name}<small>{p.sku}</small></span></button>)}</div></>}</>}{issues.length>0&&<details><summary>{issues.length} items to finish before publishing</summary><ul>{issues.map(x=><li key={x}>{x}</li>)}</ul></details>}</section>
 </div>;
}
