import React,{useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {uploadPhoto} from './media';
import ProductPicker from './ProductPicker';
import {stockPreview} from './stockMovement';

const labels={arrival:'Stock arrived',dispatch:'Stock sold / sent',count:'Count all stock'};
export default function StockIntake(){
 const [kind,setKind]=useState(''),[id,setId]=useState(()=>crypto.randomUUID()),[product,setProduct]=useState(null),[qty,setQty]=useState(''),[location,setLocation]=useState(''),[reference,setReference]=useState(''),[source,setSource]=useState('warehouse'),[photo,setPhoto]=useState(null),[hint,setHint]=useState(''),[deducted,setDeducted]=useState(false),[all,setAll]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[rows,setRows]=useState([]),[review,setReview]=useState(null),[note,setNote]=useState(''),[linked,setLinked]=useState(null);
 async function load(){const {data,error}=await supabase.from('stock_intake').select('*,products(name,sku,quantity)').order('created_at',{ascending:false}).limit(100);if(error)setMessage('Stock movement setup unavailable: '+error.message);else setRows(data);}
 useEffect(()=>{load();},[]);
 async function run(fn){if(busy)return;setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function select(p){const {data,error}=await supabase.from('products').select('id,name,sku,quantity,stock_revision').eq('id',p.id).single();if(error){setMessage(error.message);return;}setProduct(data);}
 async function submit(){
  if(qty===''||!Number.isInteger(Number(qty))||Number(qty)<0||(kind!=='count'&&Number(qty)===0))throw new Error('Enter whole-number quantity.');
  if(kind==='count'&&!all)throw new Error('Confirm that this is the total across all storage locations.');
  const {error}=await supabase.rpc('submit_stock_intake_v1',{p_id:id,p_product_id:product?.id??null,p_kind:kind,p_quantity:Number(qty),p_location:location,p_reference:reference,p_source:source,p_photo:photo,p_hint:hint,p_already_deducted:deducted,p_expected_revision:product?.stock_revision??null});if(error)throw error;
  setKind('');setId(crypto.randomUUID());setPhoto(null);setProduct(null);setQty('');setReference('');setAll(false);setDeducted(false);await load();setMessage('Sent for review. Stock has not changed.');
 }
 async function decide(approve){const {error}=await supabase.rpc('review_stock_intake_v1',{p_id:review.id,p_product_id:review.product_id||linked?.id||null,p_approve:approve,p_note:note});if(error)throw error;setReview(null);await load();setMessage(approve?'Approved and recorded.':'Rejected. Stock unchanged.');}
 const preview=review?stockPreview(linked?.quantity??review.products?.quantity,review.kind,review.quantity,review.already_deducted):null;
 const field=(label,value,setter,type='text')=><label className="cs-field"><span>{label}</span><input type={type} min="0" step="1" value={value} onChange={e=>setter(e.target.value)}/></label>;
 return <section className="cs-panel"><h1>Stock movements</h1><p>No AI calls. Record → review → update stock.</p>{message&&<p role="status">{message}</p>}<fieldset disabled={busy} style={{border:0,padding:0}}>
 {!kind&&!review&&<div className="cs-row-actions">{Object.entries(labels).map(([key,label])=><button key={key} onClick={()=>setKind(key)}>{label}</button>)}</div>}
 {review&&preview&&<p><strong>Stock preview: {preview.before} → {preview.after}</strong>{!preview.valid?' · Check quantity':''} · Rechecked when approved</p>}
 {kind&&<><h2>{labels[kind]}</h2><label className="cs-field"><span>Product photo</span><input type="file" accept="image/*" capture="environment" onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>setPhoto(await uploadPhoto(id,'movement',file,setMessage)));}}/></label>{photo&&<img className="cs-reference" src={photo.url} alt="Movement evidence"/>}{product?<p><strong>{product.name}</strong> · {product.sku} · Current stock {product.quantity}<button onClick={()=>setProduct(null)}>Change</button></p>:<ProductPicker onSelect={select}/>}<p>If unknown, add a short name and let the reviewer link it. Counts require a linked product.</p>{!product&&field('Short product name',hint,setHint)}{field(kind==='count'?'Total counted across ALL locations':'Quantity',qty,setQty,'number')}{field('Storage location / locations counted',location,setLocation)}{field('Unique shipment / order / count reference',reference,setReference)}<label className="cs-field"><span>Source</span><select value={source} onChange={e=>setSource(e.target.value)}>{['warehouse','instagram','walk-in','website','amazon'].map(s=><option key={s}>{s}</option>)}</select></label>{kind==='dispatch'&&<label className="cs-check"><input type="checkbox" checked={deducted} onChange={e=>setDeducted(e.target.checked)}/>Already deducted by website / Amazon — record only, do not subtract again</label>}{kind==='count'&&<label className="cs-check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>I counted all locations for this SKU, not just one shelf.</label>}<button className="cs-primary" disabled={!photo} onClick={()=>run(submit)}>Send for review</button><button onClick={()=>setKind('')}>Back</button></>}
 {review&&<><h2>Review {labels[review.kind]}</h2><img className="cs-reference" src={review.photo.url} alt="Recorded product"/><p>{review.products?.name||review.product_hint||'Unmatched product'} · Qty {review.quantity} · {review.location}</p><p>{review.source} · {review.reference}</p>{!review.product_id&&<ProductPicker hint={review.product_hint} onSelect={setLinked}/>}<p>{linked&&`Linked: ${linked.name}. `}{review.already_deducted?'Record only: no stock deduction.':review.kind==='count'?'Replaces total stock only if no stock movement occurred since counting.':review.kind==='arrival'?'Adds received units to current stock.':'Subtracts dispatched units from current stock.'}</p>{field('Review note / rejection reason',note,setNote)}<button className="cs-primary" onClick={()=>run(()=>decide(true))}>Approve</button><button onClick={()=>run(()=>decide(false))}>Reject</button><button onClick={()=>setReview(null)}>Back</button></>}
 {!kind&&!review&&<div className="cs-table-wrap"><table className="cs-inventory-table"><thead><tr>{['Product','Movement','Qty','Reference','Stock','Status',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.products?.name||r.product_hint||'Needs linking'}</td><td>{labels[r.kind]}</td><td>{r.quantity}</td><td>{r.source} · {r.reference}</td><td>{r.status==='approved'?`${r.before_quantity} → ${r.after_quantity}`:'Unchanged'}</td><td>{r.status}</td><td>{r.status==='pending'&&<button onClick={()=>{setReview(r);setLinked(null);setNote('');}}>Review</button>}</td></tr>)}</tbody></table></div>}
 </fieldset></section>;
}
